# Generated by Django 3.0.8 on 2020-07-15 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200713_1752'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gradedassignment',
            old_name='Assignment',
            new_name='assignment',
        ),
    ]
